# Site settings
title: Ranchlands
email: contact@ranchlands.com
description: This is the website for Land and Properties Ranchlands real estate developement outside Medicine Hat, Alberta.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
permalinks: none
# Build settings
markdown: kramdown